---
## Template file: sync_controller_networks.yaml

- hosts: {{ swarm_manager_address }}
  become: true 
  tasks:
    {% if delete -%} 
    - name: delete a docker network '{{ network_name }}'
      shell: docker network rm  {{ network_name }}
## andrew: Don't use docker_network module. This module does not work.
#      docker_network:
#        name: {{ network_name }}
#        state: absent
#        force: yes 
    {% elif duplicated -%} 
    - name: network list on swarm cluster
      shell: docker network ls
    - name: network inspection '{{ network_name }}'
      shell: docker network inspect  {{ network_name }} 
    {% else -%} 
    - name: create a docker network '{{ network_name }}'
      shell: docker network create  {{ opt_driver }}  {{ opt_ipam_driver }}  {{ opt_subnet }}  {{ opt_gateway }}  {{ opt_ipam_neutron_opt }}  {{ network_name }}
    - name: network inspection '{{ network_name }}'
      shell: docker network inspect  {{ network_name }} 
    {% endif -%} 



## andrew:  Don't use docker_network module for overlay network creation.
## [ Issue ]
##   ansible docker_network module makes some error, although overlay network is created on swarm cluster actually.

#
#   - name: Create a network with options
#       docker_network:
#         name: {{ network_name }}
#         driver: overlay
#         driver_options:
#           com.docker.network.driver.overlay.vxlanid_list: andrew_vxlanid
#         ipam_options:
#           subnet: {{ subnet }}
#           gateway: {{ gateway }}

