---
## Template file: sync_controller_slices.yaml

- hosts: {{ swarm_manager_address }}
  become: true 
  tasks:
  {% if delete -%}
    - shell: echo "delete flag={{ delete }}  login_user={{ admin_user }}"
  {% else -%}
    - shell: echo "create flag={{ delete }}  login_user={{ admin_user }}"
  {% endif %}
